### PR TITLE
feat: implement sales management, transactions PDF export, and item barcodes

### PR DESCRIPTION
**Pull request by Chris1320**

### CODE REVIEW

**Review by YuKARLO15 — APPROVED** [review]
Merged Successfully

**Comment by YuKARLO15** [comment]
Thank youu

Now ko lang na check, sa mobile pa since may inayos ako sa laptop. Will test run after nung inayos ko.

**Comment by YuKARLO15** [comment]
I could test it sooner or later, had to do a repair install of Windows pa eh

**Comment by YuKARLO15** [comment]
Okay I could test a little bit, medyo sabog pa ako now kaya I might miss something?

Pero anyways how do I fix this? (Re-install lib?)

image

**Comment by YuKARLO15** [comment]
> Okay I could test a little bit, medyo sabog pa ako now kaya I might miss something?
> 
> Pero anyways how do I fix this? (Re-install lib?)
> 
> image

Yeahh it's something sa Visual Studio eh. Pero it works naman sa may builded application na galing sa Github Actions

**Comment by Chris1320** [comment]
> > Okay I could test a little bit, medyo sabog pa ako now kaya I might miss something?
> > 
> > Pero anyways how do I fix this? (Re-install lib?)
> > 
> > image
> 
> Yeahh it's something sa Visual Studio eh. Pero it works naman sa may builded application na galing sa Github Actions

Have you tried restoring NuGet packages of the project? I added two new packages in this PR:

- Data.MySQL
- Barcode

**Comment by YuKARLO15** [comment]
Okay so I tried restoring NuGet Packages for the project but to no avail, I still have the same problem.

But it works properly when I set it to Release configuration and Run it without debugging.

I encounter the said problem when I run it on Debug configuration and Run it with debugging.

image

**Comment by YuKARLO15** [comment]
> Okay so I tried restoring NuGet Packages for the project but to no avail, I still have the same problem.
> 
> But it works properly when I set it to Release configuration and Run it without debugging.
> 
> I encounter the said problem when I run it on Debug configuration and Run it with debugging.
> 
> image

image


In the meantime, I will try to find any other solutions for the said problem.

**Pull request merged**
