### PR TITLE
feat: implement item manager

### PR DESCRIPTION
**Pull request by Chris1320**

### CODE REVIEW

**Comment by YuKARLO15** [comment]
Will this be merged or nah?

**Comment by Chris1320** [comment]
@YuKARLO15 kapag draft PR not yet

**Comment by YuKARLO15** [comment]
> @YuKARLO15 kapag draft PR not yet

Okii, muntik ko na i-merge eh hehe

**Comment by Chris1320** [comment]
@YuKARLO15 ユイチィさま, it's ready.

**Review by YuKARLO15 — APPROVED** [review]
Merged changes

**Comment by YuKARLO15** [comment]
Thank you very muchh!!

**Pull request merged**
